/**
 * Drift Protocol — Testnet Bootstrap
 *
 * Generates all required Stellar testnet keypairs, funds them via friendbot,
 * and writes a ready-to-use .env file.
 *
 * Run once:  pnpm tsx scripts/testnet-bootstrap.ts
 * Re-run:    safe — existing .env is backed up first
 */

import { Keypair, Networks } from "@stellar/stellar-sdk";
import { randomBytes } from "crypto";
import { existsSync, readFileSync, writeFileSync, copyFileSync } from "fs";
import { join } from "path";

const ROOT = join(__dirname, "..");
const ENV_PATH = join(ROOT, ".env");
const FRIENDBOT = "https://friendbot.stellar.org";
const HORIZON = "https://horizon-testnet.stellar.org";

async function friendbot(publicKey: string): Promise<void> {
  const res = await fetch(`${FRIENDBOT}?addr=${encodeURIComponent(publicKey)}`);
  if (!res.ok) throw new Error(`Friendbot failed for ${publicKey}: ${res.status} ${await res.text()}`);
  console.log(`  ✓ Funded ${publicKey.slice(0, 12)}… via friendbot`);
}

async function waitForAccount(publicKey: string, retries = 10): Promise<void> {
  for (let i = 0; i < retries; i++) {
    const res = await fetch(`${HORIZON}/accounts/${publicKey}`);
    if (res.ok) return;
    await new Promise((r) => setTimeout(r, 2000));
  }
  throw new Error(`Account ${publicKey} never appeared on Horizon`);
}

async function main() {
  console.log("\n🚀  Drift Protocol — Testnet Bootstrap\n");

  // Back up existing .env
  if (existsSync(ENV_PATH)) {
    const backup = `${ENV_PATH}.backup-${Date.now()}`;
    copyFileSync(ENV_PATH, backup);
    console.log(`📦  Backed up existing .env → ${backup}\n`);
  }

  // ── Generate keypairs ────────────────────────────────────────────────────────
  console.log("🔑  Generating keypairs…");

  const masterSeed = randomBytes(32).toString("hex");
  console.log(`  ✓ Master seed (STELLAR_MASTER_SEED): ${masterSeed.slice(0, 8)}…`);

  const sponsorKeypair = Keypair.random();
  console.log(`  ✓ Sponsor account: ${sponsorKeypair.publicKey()}`);

  const usdcIssuerKeypair = Keypair.random();
  console.log(`  ✓ Test USDC issuer: ${usdcIssuerKeypair.publicKey()}`);

  const houseKeypair = Keypair.random();
  console.log(`  ✓ House treasury: ${houseKeypair.publicKey()}`);

  // ── Fund via friendbot (parallel) ─────────────────────────────────────────
  console.log("\n💸  Funding via friendbot (testnet)…");
  await Promise.all([
    friendbot(sponsorKeypair.publicKey()),
    friendbot(usdcIssuerKeypair.publicKey()),
    friendbot(houseKeypair.publicKey()),
  ]);

  // Wait for accounts to land on Horizon
  console.log("⏳  Waiting for accounts to appear on Horizon…");
  await Promise.all([
    waitForAccount(sponsorKeypair.publicKey()),
    waitForAccount(usdcIssuerKeypair.publicKey()),
    waitForAccount(houseKeypair.publicKey()),
  ]);
  console.log("  ✓ All accounts confirmed on Horizon\n");

  // ── Write .env ─────────────────────────────────────────────────────────────
  const env = `# ── Generated by scripts/testnet-bootstrap.ts ─────────────────────────────
# Generated: ${new Date().toISOString()}
# DO NOT COMMIT THIS FILE

NODE_ENV=development

# ── Database / Cache ────────────────────────────────────────────────────────
DATABASE_URL=postgresql://drift:drift_dev@localhost:5432/drift
REDIS_URL=redis://localhost:6379

# ── API ─────────────────────────────────────────────────────────────────────
API_PORT=4000
JWT_ACCESS_SECRET=dev-jwt-secret-drift-protocol-2024
JWT_REFRESH_SECRET=dev-refresh-secret-drift-protocol-2024
REALTIME_SERVICE_TOKEN=dev-realtime-service-token
WEB_ORIGIN=http://localhost:3000,http://localhost:3004

# ── Realtime ─────────────────────────────────────────────────────────────────
REALTIME_PORT=2567

# ── Web ──────────────────────────────────────────────────────────────────────
NEXT_PUBLIC_API_URL=http://localhost:4000
NEXT_PUBLIC_REALTIME_URL=ws://localhost:2567

# ── Stellar Testnet ──────────────────────────────────────────────────────────
STELLAR_NETWORK=testnet
STELLAR_HORIZON_URL=https://horizon-testnet.stellar.org
STELLAR_NETWORK_PASSPHRASE=Test SDF Network ; September 2015

# 32-byte hex — deterministically derives all custodial player wallets
STELLAR_MASTER_SEED=${masterSeed}

# Sponsor account — funds new custodial accounts on mainnet (testnet uses friendbot)
STELLAR_SPONSOR_SECRET=${sponsorKeypair.secret()}

# Test USDC issuer — we own this on testnet so we can mint freely
STELLAR_USDC_ISSUER=${usdcIssuerKeypair.publicKey()}
STELLAR_USDC_ISSUER_SECRET=${usdcIssuerKeypair.secret()}

# House treasury — holds XLM for tournament USDC prizes
STELLAR_HOUSE_SECRET=${houseKeypair.secret()}

# Soroban contract IDs (fill in after deploying contracts)
MARKETPLACE_ESCROW_CONTRACT_ID=
TOURNAMENT_POOL_CONTRACT_ID=
ASSET_REGISTRY_CONTRACT_ID=
`;

  writeFileSync(ENV_PATH, env, "utf8");

  console.log("✅  .env written!\n");
  console.log("📋  Summary:");
  console.log(`    Stellar Network:   testnet`);
  console.log(`    USDC Issuer:       ${usdcIssuerKeypair.publicKey()}`);
  console.log(`    House Treasury:    ${houseKeypair.publicKey()}`);
  console.log(`    Sponsor:           ${sponsorKeypair.publicKey()}`);

  console.log(`
📖  Next steps:
    1. Start infrastructure:   docker compose up -d
    2. Apply migrations:       pnpm --filter @drift/api exec prisma migrate dev
    3. Seed database:          pnpm --filter @drift/api exec prisma db seed
    4. Start all services:     pnpm dev  (or run scripts/dev-start.sh)
    5. Open game:              http://localhost:3000 (or :3004)
    6. Mint test USDC:         POST /v1/wallet/airdrop  (from any logged-in session)
`);
}

main().catch((err) => {
  console.error("\n❌  Bootstrap failed:", err.message ?? err);
  process.exit(1);
});
